CREATE USER 'elecuser'@'localhost' IDENTIFIED BY 'password';

GRANT SELECT ,
INSERT ,

UPDATE ,
DELETE ,
FILE ON * . * TO 'elecuser'@'localhost' IDENTIFIED BY 'password' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;